### ISSUE TITLE
Возможность изменить создание TS файлов

### ISSUE THREAD

**Issue by nakku-tricks** [MangriMen/feature-sliced-design-components#5]
Если есть возможность, можете, пожалуйста, добавить фичу с возможностью настройки создания TS файлов. Я имею в виду, чтобы в папке ts создавался не interfaces.ts с export interface, а types.ts с export type. Это бы очень облегчило жизнь тем, кто пишет через type, а не interface

**Comment by MangriMen** [comment]
@NakkuTricks В планах на следующий апдейт как раз сделать полностью кастомизируемый шаблон, возможность их сохранять и выбирать активный. Также учту насчёт типов и добавлю вариант с типами в стандартные шаблоны

**Comment by MangriMen** [comment]
Обновил расширение и добавил пользовательские шаблоны для компонентов
